HRPayroll System/Controllers/EmployeeListController.cs
using HRPayroll_System.Data;
using HRPayroll_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;

namespace HRPayroll_System.Controllers
{
    public class EmployeeListController : Controller
    {
        private readonly HRPayrollDb hRDatabase;

        // DATABASE
        public EmployeeListController(HRPayrollDb HRDatabase)
        {
            hRDatabase = HRDatabase;
        }

        // * Routing : Contractual Employees * //

        //Contractual Employee List
        public async Task<IActionResult> List()
        {
            var Display = await hRDatabase.Employees.ToListAsync();
            return View(Display);
        }

        //Contratual ADD Employees : GET
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        //Contratual ADD Employees : POST
        [HttpPost]
        public async Task <IActionResult> Add(AddModel NewEmployee)
        {
            var Employee = new EmployeeModel()
            {

                Id = Guid.NewGuid(),
                Fullname = NewEmployee.Fullname,
                Birthday = NewEmployee.Birthday,
                TIN = NewEmployee.TIN,
                EmployeeType = NewEmployee.EmployeeType,

            };
            //Add Data To Database
            await hRDatabase.Employees.AddAsync(Employee);
            //Save Changes from the Database
            await hRDatabase.SaveChangesAsync();
            //Back to the Employee List Page
            return RedirectToAction("List");
        }

        //Contractual Edit Employee : GET
        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)


        {
            var EditEmployee = await hRDatabase.Employees.FirstOrDefaultAsync(x => x.Id == Id);

            if (EditEmployee != null)
            {
                var Employee = new EditModel()
                {

                    Id = EditEmployee.Id,
                    Fullname = EditEmployee.Fullname,
                    Birthday = EditEmployee.Birthday,
                    TIN = EditEmployee.TIN,
                    OverallTotal = EditEmployee.OverallTotal,
                    EmployeeType = EditEmployee.EmployeeType,
            };
                //Return to the Editmodel
                return View(Employee);
            }
               //Else Return to Employee List Table Page
                return RedirectToAction("List"); 
        }

        //Contractual Edit Employee : POST
        [HttpPost]
        public async Task<IActionResult> Edit(EditModel CreateEmp)
        {
            var checking = await hRDatabase.Employees.FindAsync(CreateEmp.Id);

            if(checking != null) 
            {
                checking.Fullname = CreateEmp.Fullname;
                checking.Birthday = CreateEmp.Birthday;
                checking.TIN = CreateEmp.TIN;
                checking.EmployeeType = CreateEmp.EmployeeType;
                checking.OverallTotal = CreateEmp.OverallTotal;

                await hRDatabase.SaveChangesAsync();

                return RedirectToAction("List");
            }
            return View("Edit");
        }

        //Regular Calculator : POST
        [HttpGet]
        public async Task<IActionResult> Calculator(Guid Id)
        {

            var RegularCalcu =  hRDatabase.Employees.FirstOrDefault(i => i.Id == Id);
            
            if(RegularCalcu != null)
                
            {

                var Calcu = new CalculatorModel()
                {
                    Id = RegularCalcu.Id,
                    Fullname = RegularCalcu.Fullname,
                    Birthday = RegularCalcu.Birthday,
                    TIN = RegularCalcu.TIN,
                    EmployeeType = RegularCalcu.EmployeeType,
                    TaxRate = RegularCalcu.TaxRate,
                    OverallTotal = RegularCalcu.OverallTotal,
                    RAbsences = RegularCalcu.RAbsences,
                };
                return View(Calcu); 
            }
                return RedirectToAction("List");
        }

        //Regular Calculator : POST
        [HttpPost]
        public async Task<IActionResult> Calculator(CalculatorModel RegularEmployee)
        {
            var Load = await hRDatabase.Employees.FindAsync(RegularEmployee.Id);

            if (Load != null)
            {
                int Salary = 20000;
                float Days = 22;
                float Tax = .12f;

                //Divide the salary depending of the days per month
                float PerDay = Salary / Days;
                //Get Input of the user pass to the float datatype
                float Input = RegularEmployee.RAbsences;
                //Get the difference of the Standard date to absences
                float Difference = Days - Input;
                //Get the Standard salary and tax percentage with per daysalary and absences
                float Final = Salary - ((Salary * Tax) + ( PerDay * Input));

                //Convert the into 2 Decimal place coming from Total of Salary
                string ToDecimal = Final.ToString("0.00");
                //After that convert the STring value into float to post to database
                float Finalanswer = float.Parse(ToDecimal);

                Load.RAbsences = RegularEmployee.RAbsences;
                Load.OverallTotal = Finalanswer;

                await hRDatabase.SaveChangesAsync();

                return RedirectToAction("List");

            }
            return View();

        }



        // * Routing : Contractual Employees * //

        //Contratual ADD Employees : GET
        [HttpGet]
        public IActionResult CAdd()
        {
            return View();
        }

        //Contratual ADD Employees : POST
        [HttpPost]
        public async Task<IActionResult> CAdd(CAddModel CNewEmployee)
        {
            var Employee = new EmployeeModel()
            {

                Id = Guid.NewGuid(),
                Fullname = CNewEmployee.Fullname,
                Birthday = CNewEmployee.Birthday,
                TIN = CNewEmployee.TIN,
                EmployeeType = CNewEmployee.EmployeeType,

            };
            //Add Data To Database
            await hRDatabase.Employees.AddAsync(Employee);
            //Save Changes from the Database
            await hRDatabase.SaveChangesAsync();
            //Back to the Employee List Page
            return RedirectToAction("CEmployees");
        }

        //Contractual Employee List
        public async Task <IActionResult> CEmployees()
        {
            var CList = await hRDatabase.Employees.ToListAsync();
            return View(CList);
        }

        //Contractual Calculator : GET
        [HttpGet]
        public IActionResult CCalculator(Guid Id)
        {

            var ContractualCalcu = hRDatabase.Employees.FirstOrDefault(i => i.Id == Id);

            if (ContractualCalcu != null)

            {

                var CCalcu = new CCalculatorModel()
                {
                    Id = ContractualCalcu.Id,
                    Fullname = ContractualCalcu.Fullname,
                    Birthday = ContractualCalcu.Birthday,
                    TIN = ContractualCalcu.TIN,
                    EmployeeType = ContractualCalcu.EmployeeType,
                    Ndays = ContractualCalcu.Ndays,
                };
                return View(CCalcu);
            }
                return RedirectToAction("CEmployees");
            }

        //Contractual Calculator : POST
        [HttpPost]
        public async Task<IActionResult> CCalculator(CCalculatorModel ContracttEmployee)
        {
            var Load = await hRDatabase.Employees.FindAsync(ContracttEmployee.Id);

            if (Load != null)
            {
                int Num = 500;
                float Finalanswer = ContracttEmployee.Ndays * Num;

                //Convert the into 2 Decimal place coming from Total of Salary
                string ToDecimal = Finalanswer.ToString("0.00");
                //After that convert the STring value into float to post to database
                float Total = float.Parse(ToDecimal);

                Load.Ndays= ContracttEmployee.Ndays;
                Load.OverallTotal = Total;


                await hRDatabase.SaveChangesAsync();

                return RedirectToAction("CEmployees");

            }
            return View();

        }

        //Contractual Edit Employee : GET
        [HttpGet]
        public async Task<IActionResult> CEdit(Guid Id)


        {
            var CEditEmployee = await hRDatabase.Employees.FirstOrDefaultAsync(x => x.Id == Id);

            if (CEditEmployee != null)
            {
                var CEmployee = new CEditModel()
                {

                    Id = CEditEmployee.Id,
                    Fullname = CEditEmployee.Fullname,
                    Birthday = CEditEmployee.Birthday,
                    TIN = CEditEmployee.TIN,
                    EmployeeType = CEditEmployee.EmployeeType,
                    Ndays = CEditEmployee.Ndays,
                    OverallTotal = CEditEmployee.OverallTotal,

                };
                //Return to the Editmodel
                return View(CEmployee);
            }
            //Else Return to Employee List Table Page
            return RedirectToAction("CEmployees");
        }

        //Contractual Edit Employee : POST
        [HttpPost]
        public async Task<IActionResult> CEdit(CEditModel CCreateEmp)
        {
            var Cchecking = await hRDatabase.Employees.FindAsync(CCreateEmp.Id);

            if (Cchecking != null)
            {
                Cchecking.Fullname = CCreateEmp.Fullname;
                Cchecking.Birthday = CCreateEmp.Birthday;
                Cchecking.TIN = CCreateEmp.TIN;
                Cchecking.EmployeeType = CCreateEmp.EmployeeType;
                Cchecking.Ndays = CCreateEmp.Ndays;

HRPayroll System/Views/EmployeeList/Add.cshtml
@model HRPayroll_System.Models.AddModel



<h1> Create Employee </h1

<input class="btn btn-primary" type="button" value="Home" onclick="@("window.location.href='" + @Url.Action("List", "EmployeeList") + "'");" />

<form method="post" action="Add">

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> FullName: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" placeholder="FullName" asp-for="Fullname">
        </div>
    </div>
    
    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> Birthday: </label>
        <div class="col-sm-10">
            <input class="form-control" type="Date" asp-for="Birthday" >
        </div>
    </div>

        <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> TIN: </label>
        <div class="col-sm-10">
            <input class="form-control"  type="text" oninput="Slice(this)" maxlength="15" placeholder="TIN Number" asp-for="TIN" >
        </div>
    </div>

        <label>Employee Type: </label>  

        <div class="form-check">
            <input class="form-check-input" type="radio" value="Regular"  asp-for="EmployeeType" >
            <label class="form-check-label" for="flexRadioDefault2">    Regular Employee    </label>
        </div><br />
       


        <div class="form-check">
            <input class="form-check-input" type="radio" value="Contractual"  asp-for="EmployeeType" >
            <label class="form-check-label" for="flexRadioDefault2">    Contractual Employee    </label>
        </div><br />
       

            <button asp-action="List" class="btn btn-info">Back</button>
            <button class="btn btn-primary"> Save </button>
            

</form>

    <!-- Slice Each number to 3 and maxnum for html is 15-->
    <script>
        
        function Slice(input) 
        {

          input.value = input.value.replace(/\D/g, "")
                        .replace(/(\d{3})(?=\d)/g, "$1-");

        }
    </script>

HRPayroll System/Views/EmployeeList/CAdd.cshtml
@model HRPayroll_System.Models.CAddModel
@{
}

<h1> Edit Employee </h1>

<form method="post" action="CAdd">


    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> FullName: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Fullname" />
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> Birthday: </label>
        <div class="col-sm-10">
            <input class="form-control" type="Date" asp-for="Birthday">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> TIN: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" oninput="Slice(this)" maxlength="15" placeholder="TIN Number" asp-for="TIN">
        </div>
    </div>

    <label>Employee Type: </label>

    <div class="form-check">
        <input class="form-check-input" type="radio" value="Regular" asp-for="EmployeeType">
        <label class="form-check-label" for="flexRadioDefault1">    Regular Employee    </label>
    </div>

    <div class="form-check">
        <input class="form-check-input" type="radio" value="Contractual" asp-for="EmployeeType">
        <label class="form-check-label" for="flexRadioDefault2">    Contractual Employee    </label>
    </div><br />

    <button  class="btn btn-info" asp-action="CEmployees"> Back </button>
    <button class="btn btn-primary"> Save </button>



</form>
<!-- Slice Each number to 3 and maxnum for html is 15-->
<script>

    function Slice(input) {

        input.value = input.value.replace(/\D/g, "")
            .replace(/(\d{3})(?=\d)/g, "$1-");

    }
</script>

HRPayroll System/Views/EmployeeList/CCalculator.cshtml
@model HRPayroll_System.Models.CCalculatorModel

@{
}

<h1> Contractual Calculator </h1>



<form class="row g-3" method="post" action="CCalculator">

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> ID </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Id" readonly>
        </div>
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> FullName: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" placeholder="FullName" asp-for="Fullname" readonly>
        </div>
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> TIN: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="TIN" readonly>
        </div>
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> Employee Type: </label>
        <input class="form-control" type="text" asp-for="EmployeeType" readonly />
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> Employee Type: </label>
        <input class="form-control" type="number" asp-for="EmployeeType" readonly />
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> Over all Salary: </label>
        <input id="absent" class="form-control" type="text" asp-for="OverallTotal" readonly/>

    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> No. of Days: </label>
        <input id="Absent" class="form-control" type="number" step="0.5" max="15.5" min="0" asp-for="Ndays">

    </div>

    <button id="on" class="btn btn-info" onclick="ans()"> Calculate </button>

    <button class="btn btn-info" id="sv">Save</button>


</form>
<br />
<br />


    <input class="btn btn-info" type="button" value="< Back" onclick="@("window.location.href='" + @Url.Action("CEmployees", "EmployeeList") + "'");" />



<script>

    var save = document.getElementById('sv').disabled = true;

    function ans() {

        if (confirm("Do you want to change the value?") == true) {
            var absent = document.getElementById('Absent').readOnly = true;
            var calbtn = document.getElementById('on').disabled = true;
            save = document.getElementById('sv').disabled = false;
        } else {

            location.reload(true);

        }


    }


</script>

HRPayroll System/Views/EmployeeList/CEdit.cshtml
@model HRPayroll_System.Models.CEditModel

@{
}

<h1> Edit Contractual Employee </h1> <br />

<form method="post" action="CEdit">

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> ID </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Id" readonly />
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> FullName: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Fullname" />
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> Birthday: </label>
        <div class="col-sm-10">
            <input class="form-control" type="Date" asp-for="Birthday">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> TIN: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" oninput="Slice(this)" maxlength="15" placeholder="TIN Number" asp-for="TIN">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> Overall Total: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" min="0" asp-for="OverallTotal">
        </div>
    </div>

    <label>Employee Type: </label>

    <div class="form-check">
        <input class="form-check-input" type="radio" value="Regular" asp-for="EmployeeType">
        <label class="form-check-label" for="flexRadioDefault1">    Regular Employee    </label>
    </div>

    <div class="form-check">
        <input class="form-check-input" type="radio" value="Contractual" asp-for="EmployeeType">
        <label class="form-check-label" for="flexRadioDefault2">    Contractual Employee    </label>
    </div><br />
                
            <button class="btn btn-info" asp-action="CEmployees"> Back </button>
            <button class="btn btn-primary"> Save </button>


</form>
<!-- Slice Each number to 3 and maxnum for html is 15-->
<script>

    function Slice(input) {

        input.value = input.value.replace(/\D/g, "")
            .replace(/(\d{3})(?=\d)/g, "$1-");

    }
</script>

HRPayroll System/Views/EmployeeList/CEmployees.cshtml
@model List<HRPayroll_System.Models.EmployeeModel>




<h1> Contractual Employee List </h1>
<br />


<input class="btn btn-outline-secondary" type="button" value="Create Employee" onclick="@("window.location.href='" + @Url.Action("CAdd", "EmployeeList") + "'");" />

@if (Model != null)

{
    <table class="table">

        <thread>

            <tr>

                <th> ID </th>
                <th> FullName </th>
                <th> Birthday </th>
                <th> Employee Type </th>
                <th> TIN Number </th>
                <th> Absent </th>
                <th> Salary </th>
                <th> Actions </th>


            </tr>

        </thread>

        <tbody>

            @foreach (var List in Model)
            {

                @if (List.EmployeeType == "Contractual")
                {

                    <tr>
                        <td> @List.Id </td>
                        <td> @List.Fullname </td>
                        <td> @List.Birthday </td>
                        <td> @List.EmployeeType </td>
                        <td> @List.TIN </td>
                        <td> @List.Ndays </td>
                        <td> @List.OverallTotal </td>
                        <td> <a class="btn btn-outline-info" href="CEdit/@List.Id"> Edit </a></td>
                        <td> <a class="btn btn-outline-danger" href="Delete/@List.Id"> Delete </a> </td>
                        <td> <a href="CCalculator/@List.Id"> <button class="btn btn-success"> Calculate </button> </a> </td>
                    </tr>
                }
            }

        </tbody>

    </table>

}
else
{
    //Display none
}


<input class="btn btn-info" type="button" value=" < Regular" onclick="@("window.location.href='" + @Url.Action("List", "EmployeeList") + "'");" />

HRPayroll System/Views/EmployeeList/Calculator.cshtml
@model HRPayroll_System.Models.CalculatorModel

@{
}

<h1> Regular Calculator </h1>


<form id="Calcu" class="row g-3" method="post" action="Calculator">

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> ID </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Id" readonly>
        </div>
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> FullName: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" placeholder="FullName" asp-for="Fullname" readonly>
        </div>
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> TIN: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="TIN" readonly>
        </div>
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> Employee Type: </label>
        <input class="form-control" type="text" asp-for="EmployeeType" readonly />
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> Employee Type: </label>
        <input class="form-control" type="number" asp-for="EmployeeType" readonly />
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"><b> Overall Total: </b></label>
        <input class="form-control" type="text" asp-for="OverallTotal" readonly />
    </div>

    <div class="col-md-4">
        <label for="inputEmail3" class="col-sm-4 col-form-label"> Absences: </label>
        <input id="Absent" class="form-control" type="number" step="0.5" max="22" min="0" asp-for="RAbsences" inputmode="numeric" pattern="[-+]?[0-9]*[.,]?[0-9]+"/>

    </div>

    
    <button id="on" class="btn btn-info" onclick="ans()"> Calculate </button>
   
    <button id="sv" class="btn btn-info">Save</button>
    

</form><br /> <br/>


<input class="btn btn-info" type="button" value="< Back" onclick="@("window.location.href='" + @Url.Action("List", "EmployeeList") + "'");" />



<script>

    var save = document.getElementById('sv').disabled = true;

    function ans() {

        if (confirm("Do you want to change the value?") == true) 
        {
            var absent = document.getElementById('Absent').readOnly = true;
            var calbtn = document.getElementById('on').disabled = true;
            save = document.getElementById('sv').disabled = false;
        }else 
        {   

            location.reload(true);
        
        }
        

    }


</script>

HRPayroll System/Views/EmployeeList/Edit.cshtml
@model HRPayroll_System.Models.EditModel

@{
}

<h1> Edit Employee </h1>

<form method="post" action="Edit">

        <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> ID </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" asp-for="Id" readonly/>
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> FullName: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text"  asp-for="Fullname"/>
        </div>
    </div>
    
    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> Birthday: </label>
        <div class="col-sm-10">
            <input class="form-control" type="Date" asp-for="Birthday">
        </div>
    </div>

    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> TIN: </label>
        <div class="col-sm-10">
            <input class="form-control"  type="text" oninput="Slice(this)" maxlength="15" placeholder="TIN Number" asp-for="TIN" >
        </div>
    </div>


    <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label"> Overall Total: </label>
        <div class="col-sm-10">
            <input class="form-control" type="text" min="0" asp-for="OverallTotal">
        </div>
    </div>

        <label>Employee Type: </label>  

    <div class="form-check">        
            <input class="form-check-input" type="radio" value="Regular"asp-for="EmployeeType">
            <label class="form-check-label" for="flexRadioDefault1">    Regular Employee    </label>
    </div>

    <div class="form-check">
            <input class="form-check-input" type="radio" value="Contractual"  asp-for="EmployeeType" >
            <label class="form-check-label" for="flexRadioDefault2">    Contractual Employee    </label>
    </div><br />

            <button asp-action="List" class="btn btn-info">Back</button>
            <button class="btn btn-primary"> Save </button>


</form>
    <!-- Slice Each number to 3 and maxnum for html is 15-->
    <script>
        
        function Slice(input) 
        {

          input.value = input.value.replace(/\D/g, "")
                        .replace(/(\d{3})(?=\d)/g, "$1-");

        }
    </script>

HRPayroll System/Views/EmployeeList/List.cshtml
<HRPayroll_System.Models.EditModel>




<h1> Regular Employee List </h1>  <br /> 


<input class="btn btn-outline-secondary" type="button" value="Create Employee" onclick="@("window.location.href='" + @Url.Action("Add", "EmployeeList") + "'");" />

    @if(Model != null)

    {
        <table class="table">

            <thread>

                 <tr>

                    <th> ID </th>
                    <th> FullName </th>
                    <th> Birthday </th>
                    <th> Employee Type </th>
                    <th> TIN Number </th>
                    <th> Absences </th>
                    <th> Tax Rate % </th>
                    <th> Overall Total</th>
                   <th> Actions </th>


                </tr>

            </thread>

            <tbody>

            @foreach(var List in Model)
            {
                
                @if(List.EmployeeType == "Regular")
                {

                    <tr>
                        <td> @List.Id </td>
                        <td> @List.Fullname </td>
                        <td> @List.Birthday </td>
                        <td> @List.EmployeeType </td>
                        <td> @List.TIN </td>
                        <td> @List.RAbsences </td> <!--For Regular Employee-->
                        <td> 12% </td>
                        <td> @List.OverallTotal </td>
                            <td> <a class="btn btn-outline-info" href="Edit/@List.Id"> Edit </a> </td>
                            <td> <a class="btn btn-outline-danger" href="Deletes/@List.Id"> Delete </a> </td>
                        <td> <a href="Calculator/@List.Id"> <button class="btn btn-success"> Calculate </button> </a> </td>   
                      
                    </tr>
                }
            }

            </tbody>

        </table>

    }else
    {
        //Display none
    }


    <input class="btn btn-info" type="button" value=" Contractual > " onclick="@("window.location.href='" + @Url.Action("CEmployees", "EmployeeList") + "'");" />